name: e-shape_vlab
channels:
  - defaults
  - conda-forge
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.4.0
  - backcall=0.2.0
  - bleach=4.1.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - colorama=0.4.4
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jinja2=3.0.3
  - jsonschema=3.0.2
  - jupyter_client=7.1.2
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - markupsafe=2.0.1
  - mistune=0.8.4
  - msys2-conda-epoch=20160418
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - notebook=6.4.3
  - packaging=21.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=21.2.2
  - powershell_shortcut=0.0.1
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.0.4
  - pyrsistent=0.17.3
  - python=3.6.13
  - python-dateutil=2.8.2
  - pywin32=228
  - pywinpty=0.5.7
  - pyzmq=22.2.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.39.2
  - terminado=0.9.4
  - testpath=0.5.0
  - tornado=6.1
  - traitlets=4.3.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - wincertstore=0.2
  - winpty=0.4.3
  - pip:
    - altair==4.1.0
    - asteval==0.9.26
    - branca==0.5.0
    - cachetools==4.2.4
    - cftime==1.6.0
    - charset-normalizer==2.0.12
    - cycler==0.11.0
    - earthengine-api==0.1.322
    - et-xmlfile==1.1.0
    - folium==0.12.1.post1
    - future==0.18.2
    - google-api-core==2.8.2
    - google-api-python-client==1.12.11
    - google-auth==2.11.0
    - google-auth-httplib2==0.1.0
    - google-cloud-core==2.3.1
    - google-cloud-storage==2.0.0
    - google-crc32c==1.3.0
    - google-resumable-media==2.3.3
    - googleapis-common-protos==1.56.3
    - hesseflux==4.5
    - httplib2==0.20.4
    - httplib2shim==0.0.3
    - idna==3.3
    - importlib-metadata==4.8.3
    - joblib==1.1.0
    - kiwisolver==1.3.1
    - lmfit==1.0.3
    - matplotlib==3.3.4
    - netcdf4==1.5.6
    - numpy==1.19.5
    - openpyxl==3.0.10
    - pandas==1.1.5
    - patsy==0.5.2
    - pillow==8.4.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyjams==1.26
    - pyproj==3.0.1
    - pytz==2022.2.1
    - requests==2.27.1
    - rsa==4.9
    - schwimmbad==0.3.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - seaborn==0.11.2
    - sklearn==0.0
    - statsmodels==0.12.2
    - threadpoolctl==3.1.0
    - toolz==0.12.0
    - typing-extensions==4.1.1
    - uncertainties==3.1.7
    - uritemplate==3.0.1
    - urllib3==1.26.12
    - xlrd==2.0.1
    - zipp==3.6.0